import Head from "next/head";
import Link from "next/link";
import { Header, Footer, PageIntro } from "../../components/SiteChrome";
const offerings=[
  {n:"01",title:"PCB Design Review & DFM Audit",image:"/services/18-catalog-dfm-audit-thumbnail.png",summary:"An independent review of schematic, layout and fabrication readiness before files reach the factory.",work:["Schematic and layout review","Power, grounding and return-path analysis","DFM / DFA checks","Prioritized findings with clear actions"],deliverables:["Annotated review report","Risk-ranked issue list","Manufacturing-readiness notes"],boundary:"Review and recommendations only; redesign, firmware and certification management are separate scopes."},
  {n:"02",title:"Production-Ready Custom PCB Design",image:"/services/21-catalog-custom-pcb-thumbnail.png",summary:"A complete board implementation structured around product, mechanical and manufacturing constraints.",work:["Requirements and system partitioning","Schematic capture and design checks","Placement and multilayer routing","Release-package preparation"],deliverables:["Native design files","Gerbers / ODB++, drill and drawings","BOM and pick-and-place data"],boundary:"Firmware, enclosure design, procurement, assembly and certification management are not included unless separately agreed."},
  {n:"03",title:"Schematic Capture & EDA Library Creation",image:"/services/31-catalog-schematic-libraries-thumbnail.png",summary:"Clean, editable engineering data from PDFs, legacy designs, datasheets or early circuit notes.",work:["PDF and legacy schematic rebuilds","Hierarchical schematic organization","Custom symbols and footprints","ERC and library verification"],deliverables:["Native EDA project","Annotated schematic PDF","Verified library, BOM and netlist"],boundary:"PCB layout and functional validation are outside this service unless added to the project scope."},
  {n:"04",title:"Battery-Powered Wireless / IoT PCB",image:"/services/41-catalog-wireless-low-power-thumbnail.png",summary:"Low-power connected hardware for ESP32, nRF52, LoRa, USB-C and LiPo-based products.",work:["Radio and power architecture","Charging and current-budget planning","RF-aware placement and routing","Antenna keep-outs and grounding strategy"],deliverables:["Schematic and PCB files","Manufacturing package","Power notes and DFM checklist"],boundary:"Laboratory RF tuning, firmware, compliance testing and guaranteed range or battery life are not included."},
];
export default function Services(){return <div className="site"><Head><title>PCB & Embedded Hardware Services — Dhara Rajpura</title><meta name="description" content="PCB review, production-ready board design, schematic capture, EDA libraries and low-power wireless hardware services."/></Head><Header/><main><PageIntro eyebrow="Services / 01—04" title="Focused hardware services, built around a clean handoff." copy="Choose a defined engagement or bring a product challenge. Every scope starts with constraints, ends with usable engineering files, and stays honest about its boundaries."/><section className="section section-dark"><div className="shell services-detail">{offerings.map(s=><article className="service-detail" key={s.n}><div className="service-art"><img src={s.image} alt={`${s.title} service visual`} /></div><div className="service-detail-copy"><span className="service-index">{s.n}</span><div className="tech-label text-cyan">Engineering service</div><h2>{s.title}</h2><p className="large-copy">{s.summary}</p><div className="service-columns"><div><h3>What I handle</h3><ul>{s.work.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Deliverables</h3><ul>{s.deliverables.map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="boundary"><strong>Scope boundary</strong><p>{s.boundary}</p></div></div></article>)}</div></section><section className="process-section"><div className="shell"><div className="section-title"><div className="tech-label">Process / 04 stages</div><h2>A disciplined path to release.</h2></div><ol className="process-grid"><li><span>01</span><h3>Define</h3><p>Interfaces, mechanics, power, parts and manufacturer limits.</p></li><li><span>02</span><h3>Capture</h3><p>Architecture, schematic and component-library verification.</p></li><li><span>03</span><h3>Implement</h3><p>Placement, routing, planes, checks and focused reviews.</p></li><li><span>04</span><h3>Release</h3><p>Native files and a complete manufacturing package.</p></li></ol></div></section><section className="contact-section"><div className="shell contact-grid"><div><div className="tech-label text-lime">Start with context</div><h2>Tell me what exists—and what must ship.</h2></div><div><p>Share a block diagram, schematic, mechanical constraints or current board files. I’ll help define the right hardware scope.</p><Link href="/#contact" className="button button-lime">Discuss your project ↗</Link></div></div></section></main><Footer/></div>}
