import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { AnimatePresence, motion } from "framer-motion";

const links=[['About','/#about'],['Services','/services'],['Projects','/projects'],['Experience','/#experience'],['Skills','/#skills'],['Reviews','/#reviews']];
export function Header(){const [open,setOpen]=useState(false);const {pathname}=useRouter();const isActive=href=>(href==='/services'&&pathname==='/services')||(href==='/projects'&&pathname==='/projects');return <header className="site-header"><div className="shell nav-shell"><Link href="/" className="wordmark focus-ring" aria-label="Dhara Rajpura home" aria-current={pathname==='/'?'page':undefined}><span>Dhara</span><b>Rajpura</b><i>PCB · Embedded</i></Link><nav className="desktop-nav" aria-label="Primary navigation">{links.map(([label,href])=><Link key={label} href={href} className={`nav-link focus-ring ${isActive(href)?'active':''}`} aria-current={isActive(href)?'page':undefined}>{label}</Link>)}<Link href="/#contact" className="button button-lime focus-ring">Start a project</Link></nav><button className="menu-button focus-ring" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-nav">{open?'Close':'Menu'}</button></div><AnimatePresence>{open&&<motion.nav id="mobile-nav" className="mobile-nav" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{links.map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)} className={isActive(href)?'active':''} aria-current={isActive(href)?'page':undefined}>{label}</Link>)}<Link href="/#contact" onClick={()=>setOpen(false)}>Start a project →</Link></motion.nav>}</AnimatePresence></header>}
export function Footer(){return <footer className="site-footer"><div className="shell footer-grid"><div><div className="wordmark footer-wordmark"><span>Dhara</span><b>Rajpura</b></div><p>Production-minded PCB and embedded hardware engineering.</p></div><div><span className="tech-label">Navigate</span><Link href="/services">Services</Link><Link href="/projects">Projects</Link><Link href="/#contact">Contact</Link></div><div><span className="tech-label">Contact</span><a href="mailto:dharaxrajpura@gmail.com">dharaxrajpura@gmail.com</a><a href="https://wa.me/919725417323" target="_blank" rel="noreferrer">WhatsApp</a></div></div><div className="shell footer-base"><span>© {new Date().getFullYear()} Dhara Rajpura</span><span>PCB design · Embedded hardware · Manufacturing handoff</span></div></footer>}
export function PageIntro({eyebrow,title,copy}){return <section className="page-intro grid-bg"><div className="shell"><div className="tech-label text-lime">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></div></section>}
